openapi: 3.0.0
info:
  title: Landmark API
  description: REST API для взаимодействия с Landmark сервисом.
  version: 1.0.0
servers:
  - url: http://localhost:8084

paths:
  /v1/landmarks/mathes:
    get:
      summary: запрос LandmarkMatch для построения списка рекомендаций
      operationId: "getLandmarkMatches"
      tags:
        - Landmarks
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
            format: double
        - in: query
          name: lng
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Список матчей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LandmarkMatchDto'


components:
  schemas:
    LandmarkMatchRequestDto:
      type: object
      properties:
        profileId:
          type: string
          format: uuid
        landmarksOfProfileId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        gender:
          type: string
        birthDate:
          type: string
          format: date
          example: "2017-01-01"
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double

    LandmarkMatchDto:
      type: object
      properties:
        id:
          type: string