openapi: 3.0.0
info:
  title: Landmark API
  description: REST API для взаимодействия с Landmark сервисом.
  version: 1.0.0
servers:
  - url: http://localhost:8084

paths:
  /api/v1/profiles/location:
    patch:
      summary: Обновление координат пользователя
      operationId: "updateProfileLocation"
      tags:
        - Profile
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
            format: double
        - in: query
          name: lng
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Обновлено

  /api/v1/landmarks/mathes:
    get:
      summary: запрос LandmarkMatch для построения списка рекомендаций
      operationId: "getLandmarkMatches"
      tags:
        - Landmarks
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
            format: double
        - in: query
          name: lng
          required: true
          schema:
            type: number
            format: double
        - in: query
          name: radius
          required: true
          schema:
            type: integer
        - in: query
          name: ageMin
          required: true
          schema:
            type: integer
        - in: query
          name: ageMax
          required: true
          schema:
            type: integer
        - in: query
          name: interestedIn
          required: true
          schema:
            type: string
            enum:
              - MALE
              - FEMALE
      responses:
        '200':
          description: Список матчей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LandmarkMatchDto'
components:
  schemas:
    LandmarkMatchDto:
      type: object
      properties:
        id:
          type: string
        profileId:
          type: string
          format: uuid
        soulmateId:
          type: string
          format: uuid
