openapi: 3.0.0
info:
  title: Swipe API
  description: REST API для взаимодействия с Swipe сервисом.
  version: 1.0.0
servers:
  - url: http://localhost:8083

paths:
  /v1/swipes:
    post:
      summary: Создание записи о swipe
      operationId: "swipe"
      tags:
        - Swipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwipeRequestDto'

      responses:
        '201':
          description: Успешная создание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwipeDto'

components:
  schemas:
    SwipeRequestDto:
      type: object
      properties:
        swipedUserId:
          type: string
          format: uuid
        liked:
          type: boolean

    SwipeDto:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
          format: uuid
        swipedUserId:
          type: string
          format: uuid
        liked:
          type: boolean
