openapi: 3.0.0
info:
  title: Swipe API
  description: REST API для взаимодействия с Swipe сервисом.
  version: 1.0.0
servers:
  - url: http://localhost:8083

paths:
  /api/v1/swipes:
    post:
      summary: Создание записи о swipe
      operationId: "swipe"
      tags:
        - Swipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwipeRequestDto'

      responses:
        '201':
          description: Успешная создание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SwipeDto'

  /api/v1/matches:
    get:
      summary: Список матчей для пользователя
      operationId: "match"
      tags:
        - Match
      responses:
        '200':
          description: список матчей
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/MatchDto' }

components:
  schemas:
    SwipeRequestDto:
      type: object
      required: [ swipedUserId, liked ]
      properties:
        swipedUserId:
          type: string
          format: uuid
        liked:
          type: boolean

    SwipeDto:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
          format: uuid
        swipedUserId:
          type: string
          format: uuid
        liked:
          type: boolean

    MatchDto:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
          format: uuid
        soulmateId:
          type: string
          format: uuid

