name: build and publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
    tags:
      - v*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Tag & publish to GitHub Container Registry
        run: ./gradlew common:clean build annotateFeignClients publish
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONALACCESSTOKEN }}