name: build and publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'
    tags:
      - v*

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          architecture: 'aarch64'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Tag & publish to GitHub Container Registry
        run: |
          ./gradlew publish